export interface ProductSeedInput {
  name: string;
  categorySlug: string;
  subcategory: string;
  brand: string;
  collectionName: string;
  material: string;
  finish: string;
  surface: string;
  color: string;
  size: string;
  bodyType: string;
  sku: string;
  description: string;
  applications: string[];
  specifications: { key: string; value: string }[];
  images: string[];
  installationImages: string[];
  featured: boolean;
  newArrival: boolean;
  popular: boolean;
  available: boolean;
  visible: boolean;
  displayOrder: number;
}

export const tileSeeds: ProductSeedInput[] = [
  {
    name: 'CALACATTA ORO SUPREMO',
    categorySlug: 'tiles',
    subcategory: 'Large Format Porcelain',
    brand: 'Varmora Granito',
    collectionName: 'CALACATTA & STATUARIO GRANDE',
    material: 'Glazed Vitrified Porcelain',
    finish: 'Mirror Polished',
    surface: 'Floor & Wall',
    color: 'Warm White & Gold Veining',
    size: '1200x2400 mm',
    bodyType: '9mm Slim Porcelain Slab',
    sku: 'TIL-CAL-2400',
    description: 'Monumental 9mm continuous gold-veined porcelain slab reproducing rare Tuscan golden calacatta veins with zero water absorption.',
    applications: ['Living Rooms', 'Grand Lobbies', 'Master Bathrooms', 'Feature Walls'],
    specifications: [
      { key: 'Thickness', value: '9 mm' },
      { key: 'Water Absorption', value: '< 0.05%' },
      { key: 'Surface Hardness', value: 'MOHS 7' },
      { key: 'Frost Resistance', value: '100% Guaranteed' },
      { key: 'Edge', value: 'Precision Rectified' },
    ],
    images: [
      'https://images.unsplash.com/photo-1604014237800-1c9102c219da?auto=format&fit=crop&w=1600&q=85',
      'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=1600&q=85',
    ],
    installationImages: [
      'https://images.unsplash.com/photo-1604014237800-1c9102c219da?auto=format&fit=crop&w=1600&q=85',
    ],
    featured: true,
    newArrival: true,
    popular: true,
    available: true,
    visible: true,
    displayOrder: 1,
  },
  {
    name: 'STATUARIO VENATO ROYAL',
    categorySlug: 'tiles',
    subcategory: 'Floor Tiles',
    brand: 'Kajaria Ceramics',
    collectionName: 'CALACATTA & STATUARIO GRANDE',
    material: 'Vitrified Porcelain',
    finish: 'High Gloss Polished',
    surface: 'Floor',
    color: 'Pure White & Bold Grey Vein',
    size: '800x1600 mm',
    bodyType: 'Full Body Glazed Vitrified',
    sku: 'TIL-STAT-1600',
    description: 'Bookmatched dramatic grey veining on pristine white background engineered for luxury Indian master living spaces.',
    applications: ['Living Rooms', 'Bedrooms', 'Dining Suites'],
    specifications: [
      { key: 'Thickness', value: '9.5 mm' },
      { key: 'Stain Resistance', value: 'Class 5 High Stain Proof' },
      { key: 'Chemical Resistance', value: 'Passes ISO 10545-13' },
    ],
    images: [
      'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=1600&q=85',
      'https://images.unsplash.com/photo-1599658883859-c647433ca3f0?auto=format&fit=crop&w=1600&q=85',
    ],
    installationImages: [],
    featured: true,
    newArrival: false,
    popular: true,
    available: true,
    visible: true,
    displayOrder: 2,
  },
  {
    name: 'NERO MARQUINA MATTE',
    categorySlug: 'tiles',
    subcategory: 'Wall & Accent',
    brand: 'Somany Ceramics',
    collectionName: 'MONOLITHIC CEMENT & BASALT',
    material: 'Glazed Vitrified',
    finish: 'Satin Matte',
    surface: 'Wall & Floor',
    color: 'Deep Midnight Black & White Vein',
    size: '600x1200 mm',
    bodyType: 'Glazed Vitrified',
    sku: 'TIL-NERO-1200',
    description: 'Midnight black satin matte porcelain with delicate crisp white lightning fractures for high-contrast powder rooms.',
    applications: ['Powder Rooms', 'Bar Counters', 'Accent Facades'],
    specifications: [
      { key: 'Slip Resistance', value: 'R9 Anti-Slip' },
      { key: 'Thickness', value: '9 mm' },
    ],
    images: [
      'https://images.unsplash.com/photo-1590381105924-c72589b9ef3f?auto=format&fit=crop&w=1600&q=85',
      'https://images.unsplash.com/photo-1617806118233-18e1de247200?auto=format&fit=crop&w=1600&q=85',
    ],
    installationImages: [],
    featured: true,
    newArrival: false,
    popular: false,
    available: true,
    visible: true,
    displayOrder: 3,
  },
  {
    name: 'TRAVERTINO ROMANO SATIN',
    categorySlug: 'tiles',
    subcategory: 'Large Format',
    brand: 'Varmora Granito',
    collectionName: 'TERRAZZO NOSTALGIA MODERN',
    material: 'Porcelain Slab',
    finish: 'Honed Matte',
    surface: 'Floor & Wall',
    color: 'Warm Beige & Cream Travertine',
    size: '800x2400 mm',
    bodyType: 'Through-Body Vitrified',
    sku: 'TIL-TRAV-2400',
    description: 'Subtle cross-cut Roman travertine texture rendered with organic micropores for warm Mediterranean spa bathrooms.',
    applications: ['Spa Bathrooms', 'Villas', 'Courtyards'],
    specifications: [
      { key: 'Thickness', value: '9 mm' },
      { key: 'Water Absorption', value: '0.04%' },
    ],
    images: [
      'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=1600&q=85',
      'https://images.unsplash.com/photo-1589939705384-5185137a7f0f?auto=format&fit=crop&w=1600&q=85',
    ],
    installationImages: [],
    featured: true,
    newArrival: true,
    popular: true,
    available: true,
    visible: true,
    displayOrder: 4,
  },
  {
    name: 'GREY BASALTINA CONCRETE',
    categorySlug: 'tiles',
    subcategory: 'Floor Tiles',
    brand: 'Kajaria Ceramics',
    collectionName: 'MONOLITHIC CEMENT & BASALT',
    material: 'Vitrified Body',
    finish: 'Micro-Grain Matte',
    surface: 'Floor',
    color: 'Architectural Slate Grey',
    size: '600x1200 mm',
    bodyType: 'Full Body Vitrified',
    sku: 'TIL-BAS-1200',
    description: 'Raw minimal architectural concrete micro-texture with high thermal stability and heavy foot traffic endurance.',
    applications: ['Art Galleries', 'Open Kitchens', 'Boutique Offices'],
    specifications: [
      { key: 'Abrasion Resistance', value: 'PEI V Commercial' },
      { key: 'Slip Rating', value: 'R10' },
    ],
    images: [
      'https://images.unsplash.com/photo-1541888946425-d0fbb18086f6?auto=format&fit=crop&w=1600&q=85',
      'https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=1600&q=85',
    ],
    installationImages: [],
    featured: false,
    newArrival: false,
    popular: true,
    available: true,
    visible: true,
    displayOrder: 5,
  },
  {
    name: 'CELESTIAL ONYX EMERALD',
    categorySlug: 'tiles',
    subcategory: 'Backlit Porcelain',
    brand: 'Varmora Granito',
    collectionName: 'CALACATTA & STATUARIO GRANDE',
    material: 'Translucent Vitrified Slab',
    finish: 'Ultra High Gloss Crystal',
    surface: 'Feature Wall',
    color: 'Deep Emerald Green Onyx',
    size: '1200x2800 mm',
    bodyType: 'Super Sintered Compact Surface',
    sku: 'TIL-ONYX-2800',
    description: 'Translucent jade and emerald crystal veining that responds magically to integrated LED backlighting.',
    applications: ['Living Room TV Feature', 'Hotel Lobbies', 'Luxury Bars'],
    specifications: [
      { key: 'Light Translucency', value: '18% Backlit Active' },
      { key: 'Thickness', value: '6 mm' },
    ],
    images: [
      'https://images.unsplash.com/photo-1618219908412-a29a1bb7b86e?auto=format&fit=crop&w=1600&q=85',
      'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?auto=format&fit=crop&w=1600&q=85',
    ],
    installationImages: [],
    featured: true,
    newArrival: true,
    popular: true,
    available: true,
    visible: true,
    displayOrder: 6,
  },
  {
    name: 'TERRAZZO VENETIAN FLAKES',
    categorySlug: 'tiles',
    subcategory: 'Designer Tiles',
    brand: 'Somany Ceramics',
    collectionName: 'TERRAZZO NOSTALGIA MODERN',
    material: 'Vitrified Ceramic',
    finish: 'Silk Matte',
    surface: 'Floor & Wall',
    color: 'Warm Biscuit with Carrara & Ochre Chips',
    size: '600x600 mm',
    bodyType: 'Glazed Vitrified',
    sku: 'TIL-TER-600',
    description: 'Artisanal Italian terrazzo revival incorporating genuine marble chips in warm biscuit porcelain.',
    applications: ['Boutique Cafes', 'Kitchen Islands', 'Balconies'],
    specifications: [{ key: 'Thickness', value: '9 mm' }],
    images: [
      'https://images.unsplash.com/photo-1588854337236-6889d631faa8?auto=format&fit=crop&w=1600&q=85',
      'https://images.unsplash.com/photo-1507089947368-19c1da9775ae?auto=format&fit=crop&w=1600&q=85',
    ],
    installationImages: [],
    featured: false,
    newArrival: true,
    popular: false,
    available: true,
    visible: true,
    displayOrder: 7,
  },
  {
    name: 'RUSTIC SANDSTONE ELEVATION',
    categorySlug: 'tiles',
    subcategory: 'Outdoor & Elevation',
    brand: 'Kajaria Ceramics',
    collectionName: 'RUSTIC SLATE & QUARTZITE FACADES',
    material: 'Heavy Duty Porcelain',
    finish: 'Split Rock Textured',
    surface: 'Exterior Wall',
    color: 'Ochre Sand & Rust Brown',
    size: '300x600 mm',
    bodyType: 'Exterior Grade Vitrified',
    sku: 'TIL-RUST-300600',
    description: '3D interlocking natural sandstone elevation tile resistant to monsoon efflorescence and UV weathering.',
    applications: ['Exterior Gate Facade', 'Boundary Walls', 'Terrace Pergolas'],
    specifications: [
      { key: 'UV Stability', value: 'Colorfast 25+ Years' },
      { key: 'Water Proofing', value: 'Zero Absorption' },
    ],
    images: [
      'https://images.unsplash.com/photo-1544984243-ec57ea16fe25?auto=format&fit=crop&w=1600&q=85',
    ],
    installationImages: [],
    featured: false,
    newArrival: false,
    popular: true,
    available: true,
    visible: true,
    displayOrder: 8,
  },
  {
    name: 'COTTO TUSCAN RED HERITAGE',
    categorySlug: 'tiles',
    subcategory: 'Outdoor Tiles',
    brand: 'Somany Ceramics',
    collectionName: 'TERRAZZO NOSTALGIA MODERN',
    material: 'Extruded Porcelain',
    finish: 'Natural Matte Slip-Resistant',
    surface: 'Floor',
    color: 'Terracotta Rustic Earth Red',
    size: '400x400 mm',
    bodyType: 'Heavy Traffic Vitrified',
    sku: 'TIL-COT-400',
    description: 'Timeless terracotta floor tiles with modern vitrified durability for tropical verandas and courtyards.',
    applications: ['Courtyards', 'Verandas', 'Garden Walkways'],
    specifications: [{ key: 'Slip Resistance', value: 'R11 Wet Certified' }],
    images: [
      'https://images.unsplash.com/photo-1565538810643-b5bdb714032a?auto=format&fit=crop&w=1600&q=85',
    ],
    installationImages: [],
    featured: false,
    newArrival: false,
    popular: false,
    available: true,
    visible: true,
    displayOrder: 9,
  },
  {
    name: 'SILVER MOON QUARTZ SLAB',
    categorySlug: 'tiles',
    subcategory: 'Large Format',
    brand: 'Varmora Granito',
    collectionName: 'CALACATTA & STATUARIO GRANDE',
    material: 'Sintered Stone',
    finish: 'Silken Satin',
    surface: 'Floor & Countertop',
    color: 'Silver Mist & Warm Pearl Grey',
    size: '1200x2400 mm',
    bodyType: '12mm Solid Sintered Surface',
    sku: 'TIL-SILV-2400',
    description: 'Monolithic sintered surface capable of direct thermal contact from hot cookware and zero chemical etching.',
    applications: ['Kitchen Countertops', 'Vanity Tops', 'Main Living'],
    specifications: [
      { key: 'Heat Resistance', value: 'Up to 600°C' },
      { key: 'Scratch Resistance', value: 'Diamond Blade Rated' },
    ],
    images: [
      'https://images.unsplash.com/photo-1598887142487-3c854d51d2c7?auto=format&fit=crop&w=1600&q=85',
    ],
    installationImages: [],
    featured: true,
    newArrival: false,
    popular: true,
    available: true,
    visible: true,
    displayOrder: 10,
  },
  // Distinct real images for all remaining 20 tiles
  ...[
    { name: 'ARABESCATO CORCHIA EXTRA', img: 'https://images.unsplash.com/photo-1599658883859-c647433ca3f0?auto=format&fit=crop&w=1600&q=85', color: 'White with Dramatic Dark Ovoid Veins' },
    { name: 'PIETRA GREY INTENSO', img: 'https://images.unsplash.com/photo-1501162946741-4960f990fdf4?auto=format&fit=crop&w=1600&q=85', color: 'Charcoal Grey with Pure White Filaments' },
    { name: 'MICHELANGELO BIANCO', img: 'https://images.unsplash.com/photo-1615529182904-14819c35db37?auto=format&fit=crop&w=1600&q=85', color: 'Pure Milky White Crystalline' },
    { name: 'VALENTINO BRONZE SLAB', img: 'https://images.unsplash.com/photo-1579546929518-9e396f3cc809?auto=format&fit=crop&w=1600&q=85', color: 'Deep Bronze Brown & Gold Flakes' },
    { name: 'LIME STONE CREMA NATURAL', img: 'https://images.unsplash.com/photo-1589939705384-5185137a7f0f?auto=format&fit=crop&w=1600&q=85', color: 'Warm Honey Crema' },
    { name: 'TUNDRA GREY SILK', img: 'https://images.unsplash.com/photo-1578301978693-85fa9c0320b9?auto=format&fit=crop&w=1600&q=85', color: 'Soft Fog Grey & Cloud Textures' },
    { name: 'PORTORO GOLD NOIR', img: 'https://images.unsplash.com/photo-1590381105924-c72589b9ef3f?auto=format&fit=crop&w=1600&q=85', color: 'Pitch Obsidian Black with Golden Quartz' },
    { name: 'CALACATTA GOLD VELVET', img: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=1600&q=85', color: 'Ivory White with Amber Amber Webbing' },
    { name: 'AMAZONITE EXOTIC SLAB', img: 'https://images.unsplash.com/photo-1597773150796-e5c14ebecbf5?auto=format&fit=crop&w=1600&q=85', color: 'Aquamarine Turquoise & White Spars' },
    { name: 'CONCRETE ASH ARCHITECTURAL', img: 'https://images.unsplash.com/photo-1541888946425-d0fbb18086f6?auto=format&fit=crop&w=1600&q=85', color: 'Cast In-Situ Industrial Ash Grey' },
    { name: 'PORTLAND BEIGE MATTE', img: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=1600&q=85', color: 'Pale Portland Stone Beige' },
    { name: 'FLUSH WHITE CARVED 3D', img: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=1600&q=85', color: 'Textured Geometric 3D White' },
    { name: 'SAHARA NOIR POLISHED', img: 'https://images.unsplash.com/photo-1617806118233-18e1de247200?auto=format&fit=crop&w=1600&q=85', color: 'Deep Black with Orange & White Veins' },
    { name: 'ALPINE OAK WOODEN PLANK TILE', img: 'https://images.unsplash.com/photo-1538688525198-9b88f6f53126?auto=format&fit=crop&w=1600&q=85', color: 'Nordic Natural Bleached Oak' },
    { name: 'VINTAGE WALNUT VITRIFIED PLANK', img: 'https://images.unsplash.com/photo-1516455590571-18256e5bb9ff?auto=format&fit=crop&w=1600&q=85', color: 'Deep Smoked Walnut Grain' },
    { name: 'RUSTIC TRAVERTINE BEIGE', img: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=1600&q=85', color: 'Antiqued Roman Porous Crema' },
    { name: 'ROYAL BLUE LAPIS PORCELAIN', img: 'https://images.unsplash.com/photo-1597773150796-e5c14ebecbf5?auto=format&fit=crop&w=1600&q=85', color: 'Deep Lapis Lazuli & Gold Specks' },
    { name: 'MOROCCAN GEOMETRIC ZELLIGE', img: 'https://images.unsplash.com/photo-1588854337236-6889d631faa8?auto=format&fit=crop&w=1600&q=85', color: 'Handcrafted Gloss Emerald & White' },
    { name: 'VERDE GUATEMALA MARBLE SLAB', img: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=1600&q=85', color: 'Deep Forest Green Marble' },
    { name: 'MONO WHITE ULTRA NANO POLISH', img: 'https://images.unsplash.com/photo-1615529182904-14819c35db37?auto=format&fit=crop&w=1600&q=85', color: 'Ultra Pure Nano Vitrified White' },
  ].map((item, i) => ({
    name: item.name,
    categorySlug: 'tiles',
    subcategory: i % 2 === 0 ? 'Floor Tiles' : 'Large Format Porcelain',
    brand: i % 3 === 0 ? 'Varmora Granito' : i % 3 === 1 ? 'Kajaria Ceramics' : 'Somany Ceramics',
    collectionName: i % 2 === 0 ? 'CALACATTA & STATUARIO GRANDE' : 'MONOLITHIC CEMENT & BASALT',
    material: 'Vitrified Porcelain',
    finish: ['Mirror Polished', 'Satin Matte', 'Honed', 'Micro-Grain', 'Carved 3D'][i % 5],
    surface: ['Floor', 'Wall & Floor', 'Wall', 'Countertop'][i % 4],
    color: item.color,
    size: ['600x1200 mm', '800x1600 mm', '1200x2400 mm', '200x1200 mm'][i % 4],
    bodyType: 'Glazed Vitrified Body',
    sku: `TIL-ARCH-${200 + i}`,
    description: 'Precision engineered architectural tile with calibrated flatness, zero stain permeability, and rich depth.',
    applications: ['Living Rooms', 'Lobbies', 'Boutique Spaces', 'Master Bathrooms'],
    specifications: [
      { key: 'Thickness', value: '9 mm' },
      { key: 'Water Absorption', value: '< 0.05%' },
    ],
    images: [item.img],
    installationImages: [],
    featured: i < 3,
    newArrival: i % 3 === 0,
    popular: i % 2 === 0,
    available: true,
    visible: true,
    displayOrder: 11 + i,
  })),
];

export const graniteSeeds: ProductSeedInput[] = [
  {
    name: 'BLACK GALAXY STAR PREMIUM',
    categorySlug: 'granite-marble-natural-stone',
    subcategory: 'Natural Granite Slab',
    brand: 'Architectural Heritage',
    collectionName: 'EXOTIC INDIAN GRANITE MASTERY',
    material: 'Natural Indian Granite',
    finish: 'Mirror Gloss Polish',
    surface: 'Kitchen Countertops & Steps',
    color: 'Pitch Black with Sparkling Golden Bronzite Crystals',
    size: 'Gang-Saw Slabs (10x6 ft)',
    bodyType: '20mm Solid Natural Stone',
    sku: 'GRN-BGX-SLAB',
    description: 'Original Ongole quarry Black Galaxy with uniform high-density golden bronzite spangles, calibrated to 20mm thickness.',
    applications: ['Kitchen Countertops', 'Grand Staircases', 'Monumental Sills', 'Dining Tables'],
    specifications: [
      { key: 'Thickness', value: '20 mm / 30 mm' },
      { key: 'Compressive Strength', value: '200 MPa' },
      { key: 'Density', value: '2.95 g/cm³' },
      { key: 'Origin', value: 'Chimakurthy, Andhra Pradesh' },
    ],
    images: [
      'https://images.unsplash.com/photo-1567360425618-1594206637d2?auto=format&fit=crop&w=1600&q=85',
      'https://images.unsplash.com/photo-1590381105924-c72589b9ef3f?auto=format&fit=crop&w=1600&q=85',
    ],
    installationImages: [
      'https://images.unsplash.com/photo-1567360425618-1594206637d2?auto=format&fit=crop&w=1600&q=85',
    ],
    featured: true,
    newArrival: false,
    popular: true,
    available: true,
    visible: true,
    displayOrder: 1,
  },
  {
    name: 'COLONIAL WHITE LEATHERED',
    categorySlug: 'granite-marble-natural-stone',
    subcategory: 'Granite & Quartzite',
    brand: 'Architectural Heritage',
    collectionName: 'EXOTIC INDIAN GRANITE MASTERY',
    material: 'Natural Granite',
    finish: 'Leathered / Brushed Antique',
    surface: 'Countertop & Island',
    color: 'Creamy White with Burgundy Garnet Crystals',
    size: 'Jumbo Slabs (11x6.5 ft)',
    bodyType: '20mm Natural Slab',
    sku: 'GRN-COL-WHT',
    description: 'Soft tactile leathered finish eliminating fingerprint smudges while highlighting delicate deep burgundy garnet mineral deposits.',
    applications: ['Island Countertops', 'Bathroom Vanities', 'Outdoor BBQ'],
    specifications: [
      { key: 'Thickness', value: '20 mm' },
      { key: 'Finish Type', value: 'Diamond Brushed Leather' },
    ],
    images: [
      'https://images.unsplash.com/photo-1615529182904-14819c35db37?auto=format&fit=crop&w=1600&q=85',
      'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=1600&q=85',
    ],
    installationImages: [],
    featured: true,
    newArrival: true,
    popular: true,
    available: true,
    visible: true,
    displayOrder: 2,
  },
  {
    name: 'STEEL GREY HONED',
    categorySlug: 'granite-marble-natural-stone',
    subcategory: 'Natural Granite',
    brand: 'Architectural Heritage',
    collectionName: 'EXOTIC INDIAN GRANITE MASTERY',
    material: 'Natural Granite',
    finish: 'Silky Honed Matte',
    surface: 'Flooring & Countertop',
    color: 'Anthracite Gunmetal Charcoal Grey',
    size: 'Cutter Slabs (8x3 ft)',
    bodyType: '18mm Solid Slab',
    sku: 'GRN-STL-GRY',
    description: 'Subtle charcoal crystalline structure with non-reflective matte honing tailored for modern Japandi and minimalist interiors.',
    applications: ['Flooring', 'Wall Cladding', 'Kitchen Worktops'],
    specifications: [
      { key: 'Porosity', value: '0.15%' },
      { key: 'Hardness', value: 'MOHS 6.5' },
    ],
    images: [
      'https://images.unsplash.com/photo-1501162946741-4960f990fdf4?auto=format&fit=crop&w=1600&q=85',
    ],
    installationImages: [],
    featured: true,
    newArrival: false,
    popular: false,
    available: true,
    visible: true,
    displayOrder: 3,
  },
  ...[
    { name: 'TAN BROWN ROYALE', img: 'https://images.unsplash.com/photo-1579546929518-9e396f3cc809?auto=format&fit=crop&w=1600&q=85', color: 'Deep Brown & Black Feldspar' },
    { name: 'ALASKA WHITE GRANITE', img: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=1600&q=85', color: 'Frost White with Silver Veins' },
    { name: 'RAJASTHAN BLACK FLAMED', img: 'https://images.unsplash.com/photo-1617806118233-18e1de247200?auto=format&fit=crop&w=1600&q=85', color: 'Textured Flamed Jet Black' },
    { name: 'KASHMIR GOLD EXOTIC', img: 'https://images.unsplash.com/photo-1604014237800-1c9102c219da?auto=format&fit=crop&w=1600&q=85', color: 'Warm Golden Yellow with Garnet Dots' },
    { name: 'PARADISO CLASSICO', img: 'https://images.unsplash.com/photo-1599658883859-c647433ca3f0?auto=format&fit=crop&w=1600&q=85', color: 'Multicolor Violet & Grey Swirls' },
    { name: 'HASSAN GREEN NATURAL', img: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=1600&q=85', color: 'Rich Emerald Olive Green' },
    { name: 'VIZAG BLUE GRANITE', img: 'https://images.unsplash.com/photo-1597773150796-e5c14ebecbf5?auto=format&fit=crop&w=1600&q=85', color: 'Steel Blue with Deep Wave Veins' },
    { name: 'BRAZILIAN TAJ MAHAL QUARTZITE', img: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=1600&q=85', color: 'Warm Cream & Amber Soft Waves' },
    { name: 'STATUARIO ITALIAN MARBLE SLAB', img: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=1600&q=85', color: 'Pristine Carrara White & Grey Veins' },
    { name: 'BOTTICINO CLASSICO ITALIAN', img: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=1600&q=85', color: 'Warm Italian Biscuit Crema' },
    { name: 'MICHAEL ANGELO MARBLE', img: 'https://images.unsplash.com/photo-1598887142487-3c854d51d2c7?auto=format&fit=crop&w=1600&q=85', color: 'Luminous Sculptural White' },
    { name: 'VERDE ALLIGATOR EXOTIC QUARTZITE', img: 'https://images.unsplash.com/photo-1588854337236-6889d631faa8?auto=format&fit=crop&w=1600&q=85', color: 'Exotic Crocodile Textured Dark Green' },
  ].map((item, i) => ({
    name: item.name,
    categorySlug: 'granite-marble-natural-stone',
    subcategory: i < 6 ? 'Natural Granite Slab' : 'Exotic Marble & Quartzite',
    brand: 'Architectural Heritage',
    collectionName: 'EXOTIC INDIAN GRANITE MASTERY',
    material: i > 6 ? 'Italian Marble / Quartzite' : 'Natural Indian Granite',
    finish: ['Mirror Polish', 'Leathered', 'Flamed & Brushed', 'Honed Matte'][i % 4],
    surface: 'Slab / Countertop / Flooring',
    color: item.color,
    size: 'Full Gangsaw Slab (10x6 ft)',
    bodyType: '20mm Natural Stone Slab',
    sku: `GRN-EXO-${100 + i}`,
    description: 'Direct quarry selected raw monolithic architectural stone slab with unmatched mineral richness and natural crystallization.',
    applications: ['Kitchen Islands', 'Grand Lobbies', 'Feature Pillars', 'Luxury Bathrooms'],
    specifications: [
      { key: 'Thickness', value: '20 mm Calibrated' },
      { key: 'Origin', value: i > 6 ? 'Carrara, Italy / Brazil' : 'India' },
    ],
    images: [item.img],
    installationImages: [],
    featured: i < 3,
    newArrival: i % 2 === 0,
    popular: true,
    available: true,
    visible: true,
    displayOrder: 4 + i,
  })),
];

export const woodSeeds: ProductSeedInput[] = [
  {
    name: 'ROYAL BURMESE TEAK PIVOT ENTRANCE',
    categorySlug: 'wood-works-wooden-doors-plywood',
    subcategory: 'Main Entrance Doors',
    brand: 'Architectural Woodcraft',
    collectionName: 'ROYAL HERITAGE TEAK ENTRANCES',
    material: '100% Solid Seasoned Teak Wood',
    finish: 'Matte Polyurethane Natural Oil',
    surface: 'Entrance Door',
    color: 'Rich Golden Amber Teak Grain',
    size: '8x4.5 ft (Customisable)',
    bodyType: '55mm Solid Core Pivot Door',
    sku: 'WOD-TEAK-PIV84',
    description: 'Heavy architectural grand entrance pivot door handcrafted from 40-year seasoned Burmese teak with concealed pivot hinge and brass grip handle.',
    applications: ['Villa Main Entrance', 'Penthouse Foyer', 'Luxury Bungalows'],
    specifications: [
      { key: 'Wood Specie', value: 'Tectona Grandis (Grade A Teak)' },
      { key: 'Moisture Content', value: '< 10% Kiln Dried' },
      { key: 'Hardware', value: 'Heavy Duty 250kg Concealed Floor Spring' },
      { key: 'Termite Protection', value: 'Lifetime Natural Teak Oil Resistance' },
    ],
    images: [
      'https://images.unsplash.com/photo-1546484396-fb3fc6f95f98?auto=format&fit=crop&w=1600&q=85',
      'https://images.unsplash.com/photo-1506157786151-b8491531f063?auto=format&fit=crop&w=1600&q=85',
    ],
    installationImages: [
      'https://images.unsplash.com/photo-1546484396-fb3fc6f95f98?auto=format&fit=crop&w=1600&q=85',
    ],
    featured: true,
    newArrival: true,
    popular: true,
    available: true,
    visible: true,
    displayOrder: 1,
  },
  {
    name: 'SMOKED OAK FLUTED ACOUSTIC LOUVER',
    categorySlug: 'wood-works-wooden-doors-plywood',
    subcategory: 'Wall Panelling & Louvers',
    brand: 'Greenlam Veneers',
    collectionName: 'SMOKED OAK & WALNUT ACOUSTIC LOUVERS',
    material: 'Natural Smoked Oak on Acoustic PET Felt',
    finish: 'Ultra Matte Bio-Wax',
    surface: 'Wall & Ceiling',
    color: 'Smoked Charcoal Brown Oak Slats',
    size: '2400x600x22 mm Panels',
    bodyType: 'Acoustic Backed Wood Slat Panel',
    sku: 'WOD-OAK-LOUV',
    description: 'Architectural acoustic slat wall system improving interior sound warmth while establishing rich organic wood texture.',
    applications: ['Home Theatres', 'Living Room Backdrops', 'Executive Boardrooms'],
    specifications: [
      { key: 'Acoustic Rating', value: 'NRC 0.85' },
      { key: 'Fire Rating', value: 'Class B Flame Retardant' },
    ],
    images: [
      'https://images.unsplash.com/photo-1538688525198-9b88f6f53126?auto=format&fit=crop&w=1600&q=85',
    ],
    installationImages: [],
    featured: true,
    newArrival: false,
    popular: true,
    available: true,
    visible: true,
    displayOrder: 2,
  },
  {
    name: 'CENTURY CLUB PRIME MARINE PLYWOOD',
    categorySlug: 'wood-works-wooden-doors-plywood',
    subcategory: 'Plywood & Structural Boards',
    brand: 'Century Ply',
    collectionName: 'ROYAL HERITAGE TEAK ENTRANCES',
    material: '100% Gurjan Core BWP Marine Plywood',
    finish: 'Calibrated Smooth Sanded',
    surface: 'Cabinetry & Furniture Substrate',
    color: 'Natural Wood Veneer Ply Layering',
    size: '8x4 ft Sheets (19mm)',
    bodyType: 'BWP Marine Grade (IS 710)',
    sku: 'WOD-PLY-BWP19',
    description: 'Boiling waterproof marine plywood with Glue Line Protection (GLP) and high-density imported hardwood core.',
    applications: ['Kitchen Carcasses', 'Bathroom Wardrobes', 'Exterior Furniture'],
    specifications: [
      { key: 'Standard', value: 'IS 710 Certified' },
      { key: 'Warranty', value: '30-Year Borer & Termite Proof' },
      { key: 'Emission', value: 'E0 Zero Formaldehyde' },
    ],
    images: [
      'https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&w=1600&q=85',
    ],
    installationImages: [],
    featured: false,
    newArrival: false,
    popular: true,
    available: true,
    visible: true,
    displayOrder: 3,
  },
  ...[
    { name: 'AMERICAN WALNUT NATURAL VENEER', img: 'https://images.unsplash.com/photo-1516455590571-18256e5bb9ff?auto=format&fit=crop&w=1600&q=85', color: 'Rich Chocolate Walnut Grain' },
    { name: 'MINIMALIST CONCEALED FLUSH DOOR 40MM', img: 'https://images.unsplash.com/photo-1506157786151-b8491531f063?auto=format&fit=crop&w=1600&q=85', color: 'Matte Seamless Warm White / Ash' },
    { name: 'HERITAGE CARVED MANDIR WOODEN PORTAL', img: 'https://images.unsplash.com/photo-1589939705384-5185137a7f0f?auto=format&fit=crop&w=1600&q=85', color: 'Artisan Carved Dark Teak' },
    { name: 'SLIDING BARN DOOR IN RECLAIMED TEAK', img: 'https://images.unsplash.com/photo-1524758631624-e2822e304c36?auto=format&fit=crop&w=1600&q=85', color: 'Weathered Rustic Teak Wood' },
    { name: 'SMOKED ASH TIMBER FLOORING PLANK', img: 'https://images.unsplash.com/photo-1513836279014-a89f7a76ae86?auto=format&fit=crop&w=1600&q=85', color: 'Smoked Dark Ash Hardwood' },
    { name: 'EUROPEAN WHITE OAK SOLID PLANKS', img: 'https://images.unsplash.com/photo-1502005229762-ee1b2b8ab98f?auto=format&fit=crop&w=1600&q=85', color: 'Natural Blonde European White Oak' },
    { name: 'EXTERIOR THERMOWOOD FACADE BATTENS', img: 'https://images.unsplash.com/photo-1538688525198-9b88f6f53126?auto=format&fit=crop&w=1600&q=85', color: 'Heat-Treated Caramel Pine' },
    { name: 'BWP 16MM CALIBRATED PLYWOOD SHEET', img: 'https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&w=1600&q=85', color: 'Multi-layer Calibrated Hardwood Ply' },
    { name: 'VENEERED ARCHITECTURAL LOUVERS TEAK', img: 'https://images.unsplash.com/photo-1538688525198-9b88f6f53126?auto=format&fit=crop&w=1600&q=85', color: 'Quarter Cut Burma Teak' },
    { name: 'SOLID HARDWOOD FLOATING STAIR TREADS', img: 'https://images.unsplash.com/photo-1546484396-fb3fc6f95f98?auto=format&fit=crop&w=1600&q=85', color: 'Solid Oak Edge Glued Tread' },
    { name: 'DECORATIVE BRASS INLAY WOOD DOOR', img: 'https://images.unsplash.com/photo-1506157786151-b8491531f063?auto=format&fit=crop&w=1600&q=85', color: 'Dark Walnut with Golden Brass Inlays' },
    { name: 'SYNCHRONISED TEXTURED WOOD PANEL', img: 'https://images.unsplash.com/photo-1516455590571-18256e5bb9ff?auto=format&fit=crop&w=1600&q=85', color: 'Deep Grain Embossed Walnut' },
  ].map((item, i) => ({
    name: item.name,
    categorySlug: 'wood-works-wooden-doors-plywood',
    subcategory: i % 2 === 0 ? 'Doors & Entrances' : 'Veneers & Plywood',
    brand: i % 2 === 0 ? 'Architectural Woodcraft' : 'Greenlam Veneers',
    collectionName: 'ROYAL HERITAGE TEAK ENTRANCES',
    material: i % 2 === 0 ? 'Solid Teak / Hardwood' : 'Natural Wood Veneer',
    finish: ['Natural Satin PU', 'Raw Brushed Matte', 'Polyurethane High Gloss', 'Bio Oil'][i % 4],
    surface: 'Door / Wall / Flooring / Structure',
    color: item.color,
    size: ['8x4 ft', '7x3.5 ft', '2400x1200 mm', '8x4 ft x 19mm'][i % 4],
    bodyType: 'Seasoned Hardwood / Calibrated Core',
    sku: `WOD-PROD-${100 + i}`,
    description: 'Master artisan crafted architectural woodwork balancing natural wood grain character with structural stability.',
    applications: ['Entrances', 'Wardrobes', 'Wall Paneling', 'Modular Kitchens'],
    specifications: [
      { key: 'Wood Origin', value: 'Sustainable Certified Plantation' },
      { key: 'Treatment', value: 'Vacuum Pressure Impregnation' },
    ],
    images: [item.img],
    installationImages: [],
    featured: i < 3,
    newArrival: i % 3 === 0,
    popular: true,
    available: true,
    visible: true,
    displayOrder: 4 + i,
  })),
];

export const electricalSeeds: ProductSeedInput[] = [
  {
    name: 'ARTEOR BRUSHED BRASS 8-MODULE SWITCHBOARD',
    categorySlug: 'electrical-products-lighting-switches',
    subcategory: 'Luxury Modular Switches',
    brand: 'Legrand Arteor',
    collectionName: 'BRUSHED BRASS & NOCTURNE SWITCHES',
    material: 'CNC Milled Solid Brass & Polycarbonate',
    finish: 'Brushed Brass & Matt Black Mechanism',
    surface: 'Wall Flush Mount',
    color: 'Warm Architectural Brushed Brass',
    size: '8 Module Plate (224x86 mm)',
    bodyType: 'Solid Metal Front Plate',
    sku: 'ELE-LEG-BRS8M',
    description: 'Precision milled solid brass modular faceplate featuring soft-click micro-travel switches and subtle warm LED orientation indicator.',
    applications: ['Master Bed Headboards', 'Living Room Control', 'Luxury Suites'],
    specifications: [
      { key: 'Voltage Rating', value: '240V AC 50Hz' },
      { key: 'Current Capacity', value: '16A / 25A Heavy Duty' },
      { key: 'Contact Life', value: '100,000+ Operations' },
      { key: 'Module Size', value: '8 Modular Standard Grid' },
    ],
    images: [
      'https://images.unsplash.com/photo-1558002038-1055907df827?auto=format&fit=crop&w=1600&q=85',
      'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=1600&q=85',
    ],
    installationImages: [
      'https://images.unsplash.com/photo-1558002038-1055907df827?auto=format&fit=crop&w=1600&q=85',
    ],
    featured: true,
    newArrival: true,
    popular: true,
    available: true,
    visible: true,
    displayOrder: 1,
  },
  {
    name: 'MAGNETIC ARCHITECTURAL TRACK SPOTLIGHT 15W',
    categorySlug: 'electrical-products-lighting-switches',
    subcategory: 'Architectural Lighting',
    brand: 'Havells Studio',
    collectionName: 'MAGNETIC TRACK LIGHTING PRECISION',
    material: 'Die-cast Anodized Aluminium',
    finish: 'Deep Sandblasted Matt Black',
    surface: 'Magnetic Low Voltage Ceiling Track',
    color: 'Nocturne Matt Black Spotlight',
    size: 'Ø45 x 120 mm',
    bodyType: '48V DC Magnetic Quick Snap Module',
    sku: 'ELE-TRK-SPT15',
    description: 'Anti-glare UGR<13 architectural magnetic spotlight with CRI 98 Ra color fidelity and interchangeable 24° / 38° optical lenses.',
    applications: ['Art Galleries', 'Living Rooms', 'Sculpture Accents', 'Dining Islands'],
    specifications: [
      { key: 'Wattage', value: '15 Watts COB LED' },
      { key: 'Color Rendering', value: 'CRI > 98 Ra' },
      { key: 'Color Temperature', value: '3000K Warm Architectural White' },
      { key: 'Dimming Support', value: 'DALI-2 / 0-10V / Zigbee Smart' },
    ],
    images: [
      'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=1600&q=85',
      'https://images.unsplash.com/photo-1513506003901-1e6a229e2d15?auto=format&fit=crop&w=1600&q=85',
    ],
    installationImages: [],
    featured: true,
    newArrival: true,
    popular: true,
    available: true,
    visible: true,
    displayOrder: 2,
  },
  {
    name: 'AERO-WHISPER SILENT BLDC CEILING FAN 1200MM',
    categorySlug: 'electrical-products-lighting-switches',
    subcategory: 'BLDC Ceiling Fans',
    brand: 'Schneider Electric',
    collectionName: 'BRUSHED BRASS & NOCTURNE SWITCHES',
    material: 'Hydro-formed Aerodynamic Aluminium & Real Walnut Finish',
    finish: 'Matt Gunmetal & Walnut Grain Blades',
    surface: 'Ceiling Mount',
    color: 'Gunmetal & Dark Walnut Aero Blades',
    size: '1200 mm Sweep (48 Inch)',
    bodyType: 'Brushless DC Energy Motor (28W Max)',
    sku: 'ELE-FAN-BLDC48',
    description: 'Whisper-quiet BLDC motor consuming 65% less electricity with RF remote control, sleep timer, and reversible winter mode.',
    applications: ['Master Bedrooms', 'Living Salons', 'Study Lounges'],
    specifications: [
      { key: 'Air Delivery', value: '240 CMM High Velocity' },
      { key: 'Power Consumption', value: '28 Watts at Top Speed' },
      { key: 'Noise Level', value: '< 32 dB Whisper Quiet' },
    ],
    images: [
      'https://images.unsplash.com/photo-1565814636199-ae8133055c1c?auto=format&fit=crop&w=1600&q=85',
    ],
    installationImages: [],
    featured: false,
    newArrival: false,
    popular: true,
    available: true,
    visible: true,
    displayOrder: 3,
  },
  ...[
    { name: 'SCHNEIDER UNICA ANTHRACITE 6-MODULE PLATE', img: 'https://images.unsplash.com/photo-1558002038-1055907df827?auto=format&fit=crop&w=1600&q=85', color: 'Velvet Anthracite Dark Grey' },
    { name: 'RECESSED FRAMELESS TRIMLESS COB DOWNLIGHT 12W', img: 'https://images.unsplash.com/photo-1513506003901-1e6a229e2d15?auto=format&fit=crop&w=1600&q=85', color: 'Deep Matte Dark Chrome' },
    { name: 'RECESSED LINEAR PROFILE 20W COVE SYSTEM (3 METERS)', img: 'https://images.unsplash.com/photo-1550985543-f47f38aeee65?auto=format&fit=crop&w=1600&q=85', color: 'Anodized Silver Opal Diffuser' },
    { name: 'TOUCH GLASS CAPACITIVE SMART SWITCH 4-GANG', img: 'https://images.unsplash.com/photo-1524484485831-a92ffc0de03f?auto=format&fit=crop&w=1600&q=85', color: 'Tempered Jet Black Glass' },
    { name: 'LEGRAND ARTEOR MATTE BLACK 16A UNIVERSAL SOCKET', img: 'https://images.unsplash.com/photo-1558002038-1055907df827?auto=format&fit=crop&w=1600&q=85', color: 'Nocturne Matte Black' },
    { name: 'HAVELS STUDIO DESIGNER PENDANT CHANDELIER', img: 'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=1600&q=85', color: 'Smoked Amber Glass & Brass' },
    { name: 'FLUSH STEP LIGHTER 3W FOR STAIRWAYS', img: 'https://images.unsplash.com/photo-1521783988139-89397d761dce?auto=format&fit=crop&w=1600&q=85', color: 'Recessed Warm 2700K Brass' },
    { name: 'DISTRIBUTION BOARD SPN 8-WAY ENCLOSURE MATTE', img: 'https://images.unsplash.com/photo-1558002038-1055907df827?auto=format&fit=crop&w=1600&q=85', color: 'Industrial Textured Grey Steel' },
    { name: 'SMART WI-FI AUTOMATION CONTROLLER 8-CH', img: 'https://images.unsplash.com/photo-1524484485831-a92ffc0de03f?auto=format&fit=crop&w=1600&q=85', color: 'Compact DIN Rail Grey' },
    { name: 'ARCHITECTURAL WALL WASHER LIGHT 24W', img: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=1600&q=85', color: 'Slim Linear Black Housing' },
    { name: 'BRASS RETRO TOGGLE SWITCH PLATE 2-WAY', img: 'https://images.unsplash.com/photo-1558002038-1055907df827?auto=format&fit=crop&w=1600&q=85', color: 'Aged Vintage Brass Toggle' },
    { name: 'IP65 OUTDOOR BOLLARD LIGHT ARCHITECTURAL', img: 'https://images.unsplash.com/photo-1521783988139-89397d761dce?auto=format&fit=crop&w=1600&q=85', color: 'Architectural Cast Iron Anthracite' },
  ].map((item, i) => ({
    name: item.name,
    categorySlug: 'electrical-products-lighting-switches',
    subcategory: i % 2 === 0 ? 'Switches & Sockets' : 'Architectural Lighting',
    brand: i % 2 === 0 ? 'Schneider Electric' : 'Havells Studio',
    collectionName: 'BRUSHED BRASS & NOCTURNE SWITCHES',
    material: 'Aluminium / Polycarbonate / Brass',
    finish: ['Anodized Matt Black', 'Brushed Metal', 'Powder Coated White', 'Smoked Bronze'][i % 4],
    surface: 'Ceiling / Wall / Floor',
    color: item.color,
    size: ['Standard Modular', 'Ø75 mm', '3 Meter Length', '1200 mm'][i % 4],
    bodyType: 'Architectural Grade Electrical Component',
    sku: `ELE-PROD-${100 + i}`,
    description: 'Premium architectural electrical apparatus delivering refined tactile feedback and clean modern aesthetics.',
    applications: ['Living Rooms', 'Offices', 'Bedrooms', 'Landscape'],
    specifications: [
      { key: 'Certification', value: 'ISI & CE Certified' },
      { key: 'Warranty', value: '10-Year Mechanical Warranty' },
    ],
    images: [item.img],
    installationImages: [],
    featured: i < 3,
    newArrival: i % 2 === 0,
    popular: true,
    available: true,
    visible: true,
    displayOrder: 4 + i,
  })),
];
