export const initialCategories = [
  {
    name: 'Tiles',
    slug: 'tiles',
    description: 'Large-format glazed vitrified tiles, marble looks, full body slabs, and architectural outdoor pavers.',
    image: 'https://images.unsplash.com/photo-1604014237800-1c9102c219da?auto=format&fit=crop&w=1200&q=85',
    featured: true,
    displayOrder: 1,
  },
  {
    name: 'Granite & Marble',
    slug: 'granite-marble-natural-stone',
    description: 'Exotic Indian and imported granites, pristine Italian marbles, and honed quartzite slabs for countertops and grand lobbies.',
    image: 'https://images.unsplash.com/photo-1567360425618-1594206637d2?auto=format&fit=crop&w=1200&q=85',
    featured: true,
    displayOrder: 2,
  },
  {
    name: 'Wood Works & Doors',
    slug: 'wood-works-wooden-doors-plywood',
    description: 'Solid Burmese Teak entrances, architectural flush doors, natural wood fluted louvers, and marine-grade plywood.',
    image: 'https://images.unsplash.com/photo-1546484396-fb3fc6f95f98?auto=format&fit=crop&w=1200&q=85',
    featured: true,
    displayOrder: 3,
  },
  {
    name: 'Electrical & Lighting',
    slug: 'electrical-products-lighting-switches',
    description: 'Designer brush metal switches, anti-glare magnetic track lights, architectural linear profiles, and luxury silent BLDC fans.',
    image: 'https://images.unsplash.com/photo-1558002038-1055907df827?auto=format&fit=crop&w=1200&q=85',
    featured: true,
    displayOrder: 4,
  },
  {
    name: 'Natural Stone Cladding',
    slug: 'natural-stone-cladding',
    description: 'Split-face slate, sandstone elevation veneers, and textured travertine wall panels.',
    image: 'https://images.unsplash.com/photo-1544984243-ec57ea16fe25?auto=format&fit=crop&w=1200&q=85',
    featured: false,
    displayOrder: 5,
  },
  {
    name: 'Bathroom Wellness & Vanity',
    slug: 'bathroom-wellness-vanity',
    description: 'Integrated quartz wash basins, backlit stone vanities, and moisture-resistant teak bathroom fittings.',
    image: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=1200&q=85',
    featured: false,
    displayOrder: 6,
  },
  {
    name: 'Architectural Plywood & Veneers',
    slug: 'architectural-plywood-veneers',
    description: 'E0-certified calibrated plywood, smoked oak veneers, and decorative high-pressure laminates.',
    image: 'https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&w=1200&q=85',
    featured: false,
    displayOrder: 7,
  },
  {
    name: 'Architectural Lighting Systems',
    slug: 'architectural-lighting-systems',
    description: 'CRI 97+ architectural spotlights, recessed frameless downlights, and warm pendant chandeliers.',
    image: 'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=1200&q=85',
    featured: false,
    displayOrder: 8,
  },
  {
    name: 'Smart Switches & Automation',
    slug: 'smart-switches-automation',
    description: 'Capacitive touch glass panels, retrofittable smart modules, and brass toggle switchboards.',
    image: 'https://images.unsplash.com/photo-1558002038-1055907df827?auto=format&fit=crop&w=1200&q=85',
    featured: false,
    displayOrder: 9,
  },
  {
    name: 'Exterior Elevation & Hardscaping',
    slug: 'exterior-elevation-hardscaping',
    description: 'Heavy-duty 20mm outdoor vitrified pavers, granite steps, and ventilated facade materials.',
    image: 'https://images.unsplash.com/photo-1565538810643-b5bdb714032a?auto=format&fit=crop&w=1200&q=85',
    featured: false,
    displayOrder: 10,
  },
];

export const initialCollections = [
  {
    name: 'CALACATTA & STATUARIO GRANDE',
    slug: 'calacatta-statuario-grande',
    description: 'Continuous vein-matching Italian marble-inspired porcelain slabs engineered for monumental living rooms and master suites.',
    image: 'https://images.unsplash.com/photo-1604014237800-1c9102c219da?auto=format&fit=crop&w=1200&q=85',
    bannerImage: 'https://images.unsplash.com/photo-1604014237800-1c9102c219da?auto=format&fit=crop&w=2000&q=85',
    featured: true,
    displayOrder: 1,
  },
  {
    name: 'EXOTIC INDIAN GRANITE MASTERY',
    slug: 'exotic-indian-granite-mastery',
    description: 'Rare quarried Indian granite slabs featuring high-density mirror polish and leathered tactile finishes.',
    image: 'https://images.unsplash.com/photo-1567360425618-1594206637d2?auto=format&fit=crop&w=1200&q=85',
    bannerImage: 'https://images.unsplash.com/photo-1567360425618-1594206637d2?auto=format&fit=crop&w=2000&q=85',
    featured: true,
    displayOrder: 2,
  },
  {
    name: 'ROYAL HERITAGE TEAK ENTRANCES',
    slug: 'royal-heritage-teak-entrances',
    description: 'Handcrafted solid seasoned teak wood main doors showcasing traditional brass inlay and minimal geometric reeding.',
    image: 'https://images.unsplash.com/photo-1546484396-fb3fc6f95f98?auto=format&fit=crop&w=1200&q=85',
    bannerImage: 'https://images.unsplash.com/photo-1546484396-fb3fc6f95f98?auto=format&fit=crop&w=2000&q=85',
    featured: true,
    displayOrder: 3,
  },
  {
    name: 'BRUSHED BRASS & NOCTURNE SWITCHES',
    slug: 'brushed-brass-nocturne-switches',
    description: 'Anodized aluminum and solid brass modular switch plates paired with whisper-silent tactile mechanisms.',
    image: 'https://images.unsplash.com/photo-1558002038-1055907df827?auto=format&fit=crop&w=1200&q=85',
    bannerImage: 'https://images.unsplash.com/photo-1558002038-1055907df827?auto=format&fit=crop&w=2000&q=85',
    featured: true,
    displayOrder: 4,
  },
  {
    name: 'MONOLITHIC CEMENT & BASALT',
    slug: 'monolithic-cement-basalt',
    description: 'Sleek architectural concrete aesthetics with anti-slip micro-texture for minimalist contemporary villas.',
    image: 'https://images.unsplash.com/photo-1541888946425-d0fbb18086f6?auto=format&fit=crop&w=1200&q=85',
    bannerImage: 'https://images.unsplash.com/photo-1541888946425-d0fbb18086f6?auto=format&fit=crop&w=2000&q=85',
    featured: true,
    displayOrder: 5,
  },
  {
    name: 'SMOKED OAK & WALNUT ACOUSTIC LOUVERS',
    slug: 'smoked-oak-walnut-acoustic-louvers',
    description: 'Architectural wall paneling and fluted wood batten systems delivering warm organic ambience and acoustic absorption.',
    image: 'https://images.unsplash.com/photo-1538688525198-9b88f6f53126?auto=format&fit=crop&w=1200&q=85',
    bannerImage: 'https://images.unsplash.com/photo-1538688525198-9b88f6f53126?auto=format&fit=crop&w=2000&q=85',
    featured: true,
    displayOrder: 6,
  },
  {
    name: 'TERRAZZO NOSTALGIA MODERN',
    slug: 'terrazzo-nostalgia-modern',
    description: 'Bold marble aggregate terrazzo tiles re-engineered for contemporary cafe floors and designer powder rooms.',
    image: 'https://images.unsplash.com/photo-1588854337236-6889d631faa8?auto=format&fit=crop&w=1200&q=85',
    bannerImage: 'https://images.unsplash.com/photo-1588854337236-6889d631faa8?auto=format&fit=crop&w=2000&q=85',
    featured: false,
    displayOrder: 7,
  },
  {
    name: 'MAGNETIC TRACK LIGHTING PRECISION',
    slug: 'magnetic-track-lighting-precision',
    description: 'Ultra-slim low voltage track system with interchangeable flood, spot, and pendant modules.',
    image: 'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=1200&q=85',
    bannerImage: 'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=2000&q=85',
    featured: false,
    displayOrder: 8,
  },
  {
    name: 'RUSTIC SLATE & QUARTZITE FACADES',
    slug: 'rustic-slate-quartzite-facades',
    description: 'Weatherproof 3D stone veneers engineered for high-impact exterior architectural elevations.',
    image: 'https://images.unsplash.com/photo-1544984243-ec57ea16fe25?auto=format&fit=crop&w=1200&q=85',
    bannerImage: 'https://images.unsplash.com/photo-1544984243-ec57ea16fe25?auto=format&fit=crop&w=2000&q=85',
    featured: false,
    displayOrder: 9,
  },
  {
    name: 'MINIMALIST LINEAR PROFILES',
    slug: 'minimalist-linear-profiles',
    description: 'Seamless cove and ceiling recessed LED profiles offering continuous glare-free illumination.',
    image: 'https://images.unsplash.com/photo-1513506003901-1e6a229e2d15?auto=format&fit=crop&w=1200&q=85',
    bannerImage: 'https://images.unsplash.com/photo-1513506003901-1e6a229e2d15?auto=format&fit=crop&w=2000&q=85',
    featured: false,
    displayOrder: 10,
  },
];

export const initialBrands = [
  {
    name: 'Varmora Granito',
    logo: 'https://images.unsplash.com/photo-1599305445671-ac291c95aaa9?auto=format&fit=crop&w=400&q=80',
    category: 'Tiles',
    displayOrder: 1,
  },
  {
    name: 'Kajaria Ceramics',
    logo: 'https://images.unsplash.com/photo-1599305445671-ac291c95aaa9?auto=format&fit=crop&w=400&q=80',
    category: 'Tiles',
    displayOrder: 2,
  },
  {
    name: 'Somany Ceramics',
    logo: 'https://images.unsplash.com/photo-1599305445671-ac291c95aaa9?auto=format&fit=crop&w=400&q=80',
    category: 'Tiles',
    displayOrder: 3,
  },
  {
    name: 'Schneider Electric',
    logo: 'https://images.unsplash.com/photo-1599305445671-ac291c95aaa9?auto=format&fit=crop&w=400&q=80',
    category: 'Electrical',
    displayOrder: 4,
  },
  {
    name: 'Legrand Arteor',
    logo: 'https://images.unsplash.com/photo-1599305445671-ac291c95aaa9?auto=format&fit=crop&w=400&q=80',
    category: 'Electrical',
    displayOrder: 5,
  },
  {
    name: 'Century Ply',
    logo: 'https://images.unsplash.com/photo-1599305445671-ac291c95aaa9?auto=format&fit=crop&w=400&q=80',
    category: 'Wood',
    displayOrder: 6,
  },
  {
    name: 'Greenlam Veneers',
    logo: 'https://images.unsplash.com/photo-1599305445671-ac291c95aaa9?auto=format&fit=crop&w=400&q=80',
    category: 'Wood',
    displayOrder: 7,
  },
  {
    name: 'Havells Studio',
    logo: 'https://images.unsplash.com/photo-1599305445671-ac291c95aaa9?auto=format&fit=crop&w=400&q=80',
    category: 'Lighting',
    displayOrder: 8,
  },
];

export const initialGallery = [
  {
    title: '1200x2400mm Statuario Carrara Porcelain Slab Surface',
    category: 'Tiles',
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=1600&q=85',
    locationOrSpace: 'Mirror Polish Surface',
    aspectRatio: '16:9',
    featured: true,
    displayOrder: 1,
  },
  {
    title: 'Monolithic Black Galaxy Granite Slab with Golden Bronzite Specks',
    category: 'Granite',
    image: 'https://images.unsplash.com/photo-1567360425618-1594206637d2?auto=format&fit=crop&w=1600&q=85',
    locationOrSpace: 'Quarry Mirror Polish',
    aspectRatio: '16:9',
    featured: true,
    displayOrder: 2,
  },
  {
    title: 'Solid Seasoned Burmese Teak Wood Grain & Timber Surface',
    category: 'Wood',
    image: 'https://images.unsplash.com/photo-1546484396-fb3fc6f95f98?auto=format&fit=crop&w=1600&q=85',
    locationOrSpace: 'Natural Amber Grain',
    aspectRatio: '16:9',
    featured: true,
    displayOrder: 3,
  },
  {
    title: 'Solid Brushed Brass Modular Switch Faceplate Hardware',
    category: 'Electrical',
    image: 'https://images.unsplash.com/photo-1558002038-1055907df827?auto=format&fit=crop&w=1600&q=85',
    locationOrSpace: 'Satin Brushed Finish',
    aspectRatio: '16:9',
    featured: true,
    displayOrder: 4,
  },
  {
    title: 'Cross-Cut Roman Travertine Porous Stone Slab Surface',
    category: 'Tiles',
    image: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=1600&q=85',
    locationOrSpace: 'Honed Matte Stone',
    aspectRatio: '16:9',
    featured: true,
    displayOrder: 5,
  },
  {
    title: 'Architectural Fluted Smoked Oak Acoustic Slat Louver System',
    category: 'Wood',
    image: 'https://images.unsplash.com/photo-1538688525198-9b88f6f53126?auto=format&fit=crop&w=1600&q=85',
    locationOrSpace: 'Acoustic Timber Louver',
    aspectRatio: '16:9',
    featured: true,
    displayOrder: 6,
  },
  {
    title: 'Colonial White Natural Granitic Crystalline Rock Slab',
    category: 'Granite',
    image: 'https://images.unsplash.com/photo-1615529182904-14819c35db37?auto=format&fit=crop&w=1600&q=85',
    locationOrSpace: 'Leathered Antique Stone',
    aspectRatio: '16:9',
    featured: true,
    displayOrder: 7,
  },
  {
    title: '48V Recessed Low-Voltage Architectural Magnetic Track Fixture',
    category: 'Lighting',
    image: 'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=1600&q=85',
    locationOrSpace: 'Architectural Lighting Fitting',
    aspectRatio: '16:9',
    featured: true,
    displayOrder: 8,
  },
];
