import { Product } from '../models/Product.js';
import { Category } from '../models/Category.js';

// EXACTLY 5 PRODUCTS PER CATEGORY (20 PRODUCTS TOTAL)
export const FIVE_PRODUCTS_PER_CATEGORY = [
  // 1. Tiles & Porcelain
  {
    name: 'CALACATTA ORO SUPREMO',
    slug: 'calacatta-oro-supremo-til-cal-2400',
    categorySlug: 'tiles',
    subcategory: 'Large Format Porcelain',
    brand: 'Varmora Granito',
    collectionName: 'CALACATTA & STATUARIO GRANDE',
    material: 'Glazed Vitrified Porcelain',
    finish: 'Mirror Polished',
    surface: 'Floor & Wall',
    color: 'Warm White with Gold Amber Veins',
    size: '1200x2400 mm',
    bodyType: '9mm Slim Porcelain Slab',
    sku: 'TIL-CAL-2400',
    description: 'Monumental continuous gold-veined porcelain slab surface with zero water absorption.',
    applications: ['Flooring', 'Feature Walls', 'Vanities'],
    specifications: [
      { key: 'Thickness', value: '9 mm' },
      { key: 'Water Absorption', value: '< 0.05%' },
    ],
    images: ['https://images.unsplash.com/photo-1604014237800-1c9102c219da?auto=format&fit=crop&w=1200&q=85'],
    featured: true,
    newArrival: true,
    popular: true,
    available: true,
    visible: true,
    displayOrder: 1,
  },
  {
    name: 'STATUARIO VENATO ROYAL',
    slug: 'statuario-venato-royal-til-stat-1600',
    categorySlug: 'tiles',
    subcategory: 'Floor Tiles',
    brand: 'Kajaria Ceramics',
    collectionName: 'CALACATTA & STATUARIO GRANDE',
    material: 'Vitrified Porcelain',
    finish: 'High Gloss Polished',
    surface: 'Floor',
    color: 'Pure White with Bold Grey Veining',
    size: '800x1600 mm',
    bodyType: 'Full Body Glazed Vitrified',
    sku: 'TIL-STAT-1600',
    description: 'Pure white Italian Carrara marble texture with dramatic bold grey lightning fissures.',
    applications: ['Flooring', 'Walls'],
    specifications: [{ key: 'Thickness', value: '9.5 mm' }],
    images: ['https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=1200&q=85'],
    featured: true,
    newArrival: false,
    popular: true,
    available: true,
    visible: true,
    displayOrder: 2,
  },
  {
    name: 'NERO MARQUINA MATTE',
    slug: 'nero-marquina-matte-til-nero-1200',
    categorySlug: 'tiles',
    subcategory: 'Wall & Accent',
    brand: 'Somany Ceramics',
    collectionName: 'MONOLITHIC CEMENT & BASALT',
    material: 'Glazed Vitrified',
    finish: 'Satin Matte',
    surface: 'Wall & Floor',
    color: 'Deep Midnight Black with White Vein',
    size: '600x1200 mm',
    bodyType: 'Glazed Vitrified',
    sku: 'TIL-NERO-1200',
    description: 'Obsidian midnight black marble slab texture with delicate crisp white lightning fractures.',
    applications: ['Feature Walls', 'Bathrooms'],
    specifications: [{ key: 'Thickness', value: '9 mm' }],
    images: ['https://images.unsplash.com/photo-1617806118233-18e1de247200?auto=format&fit=crop&w=1200&q=85'],
    featured: true,
    newArrival: false,
    popular: false,
    available: true,
    visible: true,
    displayOrder: 3,
  },
  {
    name: 'TRAVERTINO ROMANO SATIN',
    slug: 'travertino-romano-satin-til-trav-2400',
    categorySlug: 'tiles',
    subcategory: 'Large Format',
    brand: 'Varmora Granito',
    collectionName: 'TERRAZZO NOSTALGIA MODERN',
    material: 'Porcelain Slab',
    finish: 'Honed Matte',
    surface: 'Floor & Wall',
    color: 'Warm Beige & Cream Travertine',
    size: '800x2400 mm',
    bodyType: 'Through-Body Vitrified',
    sku: 'TIL-TRAV-2400',
    description: 'Cross-cut Roman travertine natural stone texture with organic micropores.',
    applications: ['Floors', 'Walls'],
    specifications: [{ key: 'Thickness', value: '9 mm' }],
    images: ['https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=1200&q=85'],
    featured: true,
    newArrival: true,
    popular: true,
    available: true,
    visible: true,
    displayOrder: 4,
  },
  {
    name: 'GREY BASALTINA CONCRETE',
    slug: 'grey-basaltina-concrete-til-bas-1200',
    categorySlug: 'tiles',
    subcategory: 'Floor Tiles',
    brand: 'Kajaria Ceramics',
    collectionName: 'MONOLITHIC CEMENT & BASALT',
    material: 'Vitrified Body',
    finish: 'Micro-Grain Matte',
    surface: 'Floor',
    color: 'Architectural Cast Slate Grey',
    size: '600x1200 mm',
    bodyType: 'Full Body Vitrified',
    sku: 'TIL-BAS-1200',
    description: 'Cast architectural concrete and slate basalt micro-texture surface.',
    applications: ['Flooring', 'Cladding'],
    specifications: [{ key: 'Abrasion Resistance', value: 'PEI V Commercial' }],
    images: ['https://images.unsplash.com/photo-1541888946425-d0fbb18086f6?auto=format&fit=crop&w=1200&q=85'],
    featured: false,
    newArrival: false,
    popular: true,
    available: true,
    visible: true,
    displayOrder: 5,
  },

  // 2. Granite & Natural Stone
  {
    name: 'BLACK GALAXY STAR PREMIUM',
    slug: 'black-galaxy-star-premium-grn-bgx-slab',
    categorySlug: 'granite-marble-natural-stone',
    subcategory: 'Natural Granite Slab',
    brand: 'Architectural Heritage',
    collectionName: 'EXOTIC INDIAN GRANITE MASTERY',
    material: 'Natural Indian Granite',
    finish: 'Mirror Gloss Polish',
    surface: 'Kitchen Countertops & Steps',
    color: 'Pitch Black with Golden Bronzite Crystals',
    size: 'Gang-Saw Slabs (10x6 ft)',
    bodyType: '20mm Solid Natural Stone',
    sku: 'GRN-BGX-SLAB',
    description: 'High-density golden bronzite sparkling crystals on pitch-black natural granite slab surface.',
    applications: ['Countertops', 'Steps', 'Table Tops'],
    specifications: [
      { key: 'Thickness', value: '20 mm / 30 mm' },
      { key: 'Compressive Strength', value: '200 MPa' },
    ],
    images: ['https://images.unsplash.com/photo-1567360425618-1594206637d2?auto=format&fit=crop&w=1200&q=85'],
    featured: true,
    newArrival: false,
    popular: true,
    available: true,
    visible: true,
    displayOrder: 21,
  },
  {
    name: 'COLONIAL WHITE LEATHERED',
    slug: 'colonial-white-leathered-grn-col-wht',
    categorySlug: 'granite-marble-natural-stone',
    subcategory: 'Granite & Quartzite',
    brand: 'Architectural Heritage',
    collectionName: 'EXOTIC INDIAN GRANITE MASTERY',
    material: 'Natural Granite',
    finish: 'Leathered / Brushed Antique',
    surface: 'Countertop & Island',
    color: 'Creamy White with Burgundy Garnet Crystals',
    size: 'Jumbo Slabs (11x6.5 ft)',
    bodyType: '20mm Natural Slab',
    sku: 'GRN-COL-WHT',
    description: 'Off-white natural stone surface textured with deep burgundy garnet crystals.',
    applications: ['Islands', 'Countertops'],
    specifications: [{ key: 'Thickness', value: '20 mm' }],
    images: ['https://images.unsplash.com/photo-1615529182904-14819c35db37?auto=format&fit=crop&w=1200&q=85'],
    featured: true,
    newArrival: true,
    popular: true,
    available: true,
    visible: true,
    displayOrder: 22,
  },
  {
    name: 'STEEL GREY HONED',
    slug: 'steel-grey-honed-grn-stl-gry',
    categorySlug: 'granite-marble-natural-stone',
    subcategory: 'Natural Granite',
    brand: 'Architectural Heritage',
    collectionName: 'EXOTIC INDIAN GRANITE MASTERY',
    material: 'Natural Granite',
    finish: 'Silky Honed Matte',
    surface: 'Flooring & Countertop',
    color: 'Anthracite Gunmetal Charcoal Grey',
    size: 'Cutter Slabs (8x3 ft)',
    bodyType: '18mm Calibrated Stone',
    sku: 'GRN-STL-GRY',
    description: 'Uniform gunmetal charcoal natural granite surface with soft tactile finish.',
    applications: ['Floors', 'Vanity Slabs'],
    specifications: [{ key: 'Thickness', value: '18 mm' }],
    images: ['https://images.unsplash.com/photo-1501162946741-4960f990fdf4?auto=format&fit=crop&w=1200&q=85'],
    featured: false,
    newArrival: false,
    popular: true,
    available: true,
    visible: true,
    displayOrder: 23,
  },
  {
    name: 'TAN BROWN ROYALE',
    slug: 'tan-brown-royale-grn-tan-brn',
    categorySlug: 'granite-marble-natural-stone',
    subcategory: 'Natural Granite',
    brand: 'Architectural Heritage',
    collectionName: 'EXOTIC INDIAN GRANITE MASTERY',
    material: 'Natural Granite',
    finish: 'High Gloss Polish',
    surface: 'Cladding & Stairs',
    color: 'Chestnut Chocolate Brown with Black Crystals',
    size: 'Gang-Saw Slabs (10x6 ft)',
    bodyType: '20mm Solid Stone',
    sku: 'GRN-TAN-BRN',
    description: 'Warm copper, chocolate, and dark quartz crystalline matrix natural stone texture.',
    applications: ['Staircases', 'Exterior Facades'],
    specifications: [{ key: 'Thickness', value: '20 mm' }],
    images: ['https://images.unsplash.com/photo-1579546929518-9e396f3cc809?auto=format&fit=crop&w=1200&q=85'],
    featured: false,
    newArrival: false,
    popular: false,
    available: true,
    visible: true,
    displayOrder: 24,
  },
  {
    name: 'BRAZILIAN TAJ MAHAL QUARTZITE',
    slug: 'brazilian-taj-mahal-quartzite-grn-taj-mah',
    categorySlug: 'granite-marble-natural-stone',
    subcategory: 'Exotic Quartzite',
    brand: 'Architectural Heritage',
    collectionName: 'EXOTIC INDIAN GRANITE MASTERY',
    material: 'Natural Exotic Quartzite',
    finish: 'Polished / Leathered',
    surface: 'Island & Countertop',
    color: 'Warm Translucent Cream with Soft Amber Veins',
    size: 'Jumbo Slabs (11x6.5 ft)',
    bodyType: '20mm Solid Quartzite',
    sku: 'GRN-TAJ-MAH',
    description: 'Translucent Brazilian quartzite slab with high chemical and scratch resistance.',
    applications: ['Waterfall Islands', 'Master Vanity', 'Feature Walls'],
    specifications: [{ key: 'Thickness', value: '20 mm' }, { key: 'Mohs Hardness', value: '7' }],
    images: ['https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=1200&q=85'],
    featured: true,
    newArrival: true,
    popular: true,
    available: true,
    visible: true,
    displayOrder: 25,
  },

  // 3. Wood Works & Doors
  {
    name: 'ROYAL BURMESE TEAK PIVOT ENTRANCE',
    slug: 'royal-burmese-teak-pivot-entrance-wood-piv-tek',
    categorySlug: 'wood-works-wooden-doors-plywood',
    subcategory: 'Main Entrance Doors',
    brand: 'Greenlam Veneers',
    collectionName: 'ROYAL HERITAGE TEAK ENTRANCES',
    material: '100% Grade-A Seasoned Burmese Teak',
    finish: 'Hand-Rubbed Matte Polyurethane',
    surface: 'Heavy Duty Entrance',
    color: 'Rich Golden Honey Amber Grain',
    size: '8x4 ft (Customizable up to 10x5 ft)',
    bodyType: '55mm Solid Core Hardwood',
    sku: 'WOOD-PIV-TEK',
    description: 'Handcrafted solid seasoned teak wood main door showcasing traditional brass inlay and minimal geometric reeding.',
    applications: ['Villas', 'Main Doors', 'Penthouse Entries'],
    specifications: [
      { key: 'Door Thickness', value: '55 mm' },
      { key: 'Hardware Compatibility', value: 'Concealed 300kg Pivot Bearing' },
    ],
    images: ['https://images.unsplash.com/photo-1546484396-fb3fc6f95f98?auto=format&fit=crop&w=1200&q=85'],
    featured: true,
    newArrival: false,
    popular: true,
    available: true,
    visible: true,
    displayOrder: 41,
  },
  {
    name: 'SMOKED OAK FLUTED ACOUSTIC LOUVER',
    slug: 'smoked-oak-fluted-acoustic-louver-wood-flt-oak',
    categorySlug: 'wood-works-wooden-doors-plywood',
    subcategory: 'Architectural Louvers',
    brand: 'Greenlam Veneers',
    collectionName: 'SMOKED OAK & WALNUT ACOUSTIC LOUVERS',
    material: 'Natural Smoked Oak over Sound-Dampening Felt',
    finish: 'Natural Low VOC Oil Finish',
    surface: 'Interior Wall & Ceiling Paneling',
    color: 'Smoked Charcoal Oak & Black Felt',
    size: '2400x600x22 mm Panels',
    bodyType: 'Acoustic Composite Slat Panel',
    sku: 'WOOD-FLT-OAK',
    description: 'Architectural wall paneling and fluted wood batten systems delivering warm organic ambience and acoustic absorption.',
    applications: ['Feature Walls', 'Ceilings', 'Home Theatres'],
    specifications: [{ key: 'Acoustic Rating', value: 'NRC 0.85' }],
    images: ['https://images.unsplash.com/photo-1538688525198-9b88f6f53126?auto=format&fit=crop&w=1200&q=85'],
    featured: true,
    newArrival: true,
    popular: true,
    available: true,
    visible: true,
    displayOrder: 42,
  },
  {
    name: 'CENTURY CLUB PRIME MARINE PLYWOOD',
    slug: 'century-club-prime-marine-plywood-wood-ply-bwp',
    categorySlug: 'wood-works-wooden-doors-plywood',
    subcategory: 'Structural Plywood',
    brand: 'Century Ply',
    collectionName: 'ROYAL HERITAGE TEAK ENTRANCES',
    material: '100% Calibrated Gurjan Hardwood Timber',
    finish: 'Calibrated Smooth Sanded Surface',
    surface: 'Carcass & High-Moisture Substrates',
    color: 'Natural Wood Grain Hardwood',
    size: '8x4 ft Sheets (19mm)',
    bodyType: 'IS:710 Marine Grade Boiling Waterproof',
    sku: 'WOOD-PLY-BWP',
    description: 'Boiling waterproof calibrated marine plywood with un-extended BWP synthetic resin bonding.',
    applications: ['Kitchen Carcass', 'Vanities', 'Wardrobes'],
    specifications: [
      { key: 'Boiling Water Test', value: '72 Hours Undetached' },
      { key: 'Borer & Termite Proof', value: 'Lifetime Warranty' },
    ],
    images: ['https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&w=1200&q=85'],
    featured: false,
    newArrival: false,
    popular: true,
    available: true,
    visible: true,
    displayOrder: 43,
  },
  {
    name: 'AMERICAN WALNUT NATURAL VENEER',
    slug: 'american-walnut-natural-veneer-wood-ven-wal',
    categorySlug: 'wood-works-wooden-doors-plywood',
    subcategory: 'Architectural Veneers',
    brand: 'Greenlam Veneers',
    collectionName: 'SMOKED OAK & WALNUT ACOUSTIC LOUVERS',
    material: 'Natural Crown Cut American Walnut Wood',
    finish: 'Raw Spliced Sheet / Pre-Finished Option',
    surface: 'Wardrobe Doors & Wall Paneling',
    color: 'Deep Espresso & Warm Caramel Cathedrals',
    size: '8x4 ft Sheets (0.55mm Face)',
    bodyType: 'Fleece-Backed Natural Wood Veneer',
    sku: 'WOOD-VEN-WAL',
    description: 'Sustainably harvested North American walnut veneer with crown-cut grain structures.',
    applications: ['Paneling', 'Wardrobes', 'Bespoke Furniture'],
    specifications: [{ key: 'Face Thickness', value: '0.55 mm' }],
    images: ['https://images.unsplash.com/photo-1516455590571-18256e5bb9ff?auto=format&fit=crop&w=1200&q=85'],
    featured: true,
    newArrival: false,
    popular: true,
    available: true,
    visible: true,
    displayOrder: 44,
  },
  {
    name: 'MINIMALIST CONCEALED FLUSH DOOR 40MM',
    slug: 'minimalist-concealed-flush-door-40mm-wood-fls-40',
    categorySlug: 'wood-works-wooden-doors-plywood',
    subcategory: 'Internal Doors',
    brand: 'Century Ply',
    collectionName: 'ROYAL HERITAGE TEAK ENTRANCES',
    material: 'Solid Pinewood Battens with Gurjan Face',
    finish: 'Primer Coated / Ready for PU or Veneer',
    surface: 'Internal Bed & Bath Doors',
    color: 'Neutral White Primer',
    size: '7x3.25 ft (40mm Thickness)',
    bodyType: 'IS:2202 Solid Tubular Core',
    sku: 'WOOD-FLS-40',
    description: 'Concealed hinge compatible flush door with calibrated timber frame to avoid warping.',
    applications: ['Bedrooms', 'Internal Partitions'],
    specifications: [{ key: 'Thickness', value: '40 mm' }],
    images: ['https://images.unsplash.com/photo-1506157786151-b8491531f063?auto=format&fit=crop&w=1200&q=85'],
    featured: false,
    newArrival: false,
    popular: false,
    available: true,
    visible: true,
    displayOrder: 45,
  },

  // 4. Electrical Products & Lighting
  {
    name: 'LEGRAND ARTEOR BRUSHED BRASS SWITCH',
    slug: 'legrand-arteor-brushed-brass-switch-elc-art-brs',
    categorySlug: 'electrical-products-lighting-switches',
    subcategory: 'Designer Switches',
    brand: 'Legrand Arteor',
    collectionName: 'BRUSHED BRASS & NOCTURNE SWITCHES',
    material: 'Solid Brushed Brass Alloy Plate & Polymer Core',
    finish: 'Anti-Fingerprint Satin Brushed Gold',
    surface: 'Modular Wall Box Mount',
    color: 'Warm Brushed Brass with Black Rocker',
    size: '8-Module Plate (224x86 mm)',
    bodyType: 'Solid Metal Faceplate System',
    sku: 'ELC-ART-BRS',
    description: 'Anodized aluminum and solid brass modular switch plates paired with whisper-silent tactile mechanisms.',
    applications: ['Master Bedrooms', 'Living Rooms', 'Boardrooms'],
    specifications: [
      { key: 'Voltage Rating', value: '240V AC, 10AX / 16A' },
      { key: 'Mechanism Life', value: '100,000 Click Tested' },
    ],
    images: ['https://images.unsplash.com/photo-1558002038-1055907df827?auto=format&fit=crop&w=1200&q=85'],
    featured: true,
    newArrival: false,
    popular: true,
    available: true,
    visible: true,
    displayOrder: 61,
  },
  {
    name: '48V RECESSED MAGNETIC TRACK SYSTEM',
    slug: '48v-recessed-magnetic-track-system-elc-trk-48v',
    categorySlug: 'electrical-products-lighting-switches',
    subcategory: 'Architectural Lighting',
    brand: 'Havells Studio',
    collectionName: 'MAGNETIC TRACK LIGHTING PRECISION',
    material: 'Extruded Aircraft Grade 6063 Aluminum Profile',
    finish: 'Anodized Matte Deep Charcoal Black',
    surface: 'Ceiling Recessed Trimless Channel',
    color: 'Matte Nocturne Black Channel',
    size: '2-Meter Continuous Track Profile',
    bodyType: 'Low-Voltage 48V DC Safe System',
    sku: 'ELC-TRK-48V',
    description: 'Ultra-slim low voltage track system with interchangeable flood, spot, and pendant modules.',
    applications: ['Living Rooms', 'Galleries', 'Kitchens'],
    specifications: [
      { key: 'System Voltage', value: '48V DC Safe Touch' },
      { key: 'CRI (Color Rendering)', value: 'CRI > 97, R9 > 85' },
    ],
    images: ['https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=1200&q=85'],
    featured: true,
    newArrival: true,
    popular: true,
    available: true,
    visible: true,
    displayOrder: 62,
  },
  {
    name: 'SCHNEIDER AVATARON CRYSTAL GLASS SWITCH',
    slug: 'schneider-avataron-crystal-glass-switch-elc-sch-gls',
    categorySlug: 'electrical-products-lighting-switches',
    subcategory: 'Smart & Luxury Switches',
    brand: 'Schneider Electric',
    collectionName: 'BRUSHED BRASS & NOCTURNE SWITCHES',
    material: '4mm Beveled Toughened Crystal Glass Face',
    finish: 'Frameless Mirror White Glass',
    surface: 'Flush Wall Mount Plate',
    color: 'Pure Arctic White Glass with LED Indicator',
    size: '6-Module Plate (200x86 mm)',
    bodyType: 'Frameless Glass Cover System',
    sku: 'ELC-SCH-GLS',
    description: 'Frameless toughened crystal glass switch plate with soft phosphor LED night locating beacons.',
    applications: ['Villas', 'Master Suites', 'Modern Partitions'],
    specifications: [{ key: 'Glass Grade', value: '4mm Tempered High-Clarity' }],
    images: ['https://images.unsplash.com/photo-1524484485831-a92ffc0de03f?auto=format&fit=crop&w=1200&q=85'],
    featured: false,
    newArrival: false,
    popular: true,
    available: true,
    visible: true,
    displayOrder: 63,
  },
  {
    name: 'HAVELLS STEALTH AIR BLDC CEILING FAN',
    slug: 'havells-stealth-air-bldc-ceiling-fan-elc-fan-bldc',
    categorySlug: 'electrical-products-lighting-switches',
    subcategory: 'Luxury BLDC Fans',
    brand: 'Havells Studio',
    collectionName: 'BRUSHED BRASS & NOCTURNE SWITCHES',
    material: 'Aero-Foil ABS Blades with Solid Walnut Wood Veneer',
    finish: 'Matte Walnut Grain & Gunmetal Motor Casing',
    surface: 'Ceiling Hook Suspension Mount',
    color: 'Dark Walnut Wood Grain & Gunmetal Trim',
    size: '1250 mm Sweep (50 Inch)',
    bodyType: 'Super-Efficient 32W Inverter BLDC Motor',
    sku: 'ELC-FAN-BLDC',
    description: 'Aero-foil contoured blades engineered for silent whisper airflow and 60% energy savings with RF remote.',
    applications: ['Living Rooms', 'Master Bedrooms', 'Covered Verandas'],
    specifications: [
      { key: 'Power Consumption', value: '32 Watts at Top Speed' },
      { key: 'Air Delivery', value: '280 CMM High Velocity' },
    ],
    images: ['https://images.unsplash.com/photo-1565814636199-ae8133055c1c?auto=format&fit=crop&w=1200&q=85'],
    featured: true,
    newArrival: false,
    popular: true,
    available: true,
    visible: true,
    displayOrder: 64,
  },
  {
    name: 'DARK LIGHT ARCHITECTURAL COB DOWNLIGHT',
    slug: 'dark-light-architectural-cob-downlight-elc-drk-cob',
    categorySlug: 'electrical-products-lighting-switches',
    subcategory: 'Architectural Lighting',
    brand: 'Havells Studio',
    collectionName: 'MINIMALIST LINEAR PROFILES',
    material: 'Die-Cast Aluminum with Deep Black Anti-Glare Cone',
    finish: 'Trimless Gypsum Plaster-In Frame',
    surface: 'False Ceiling Recessed Mount',
    color: 'Trimless White with Deep Midnight Specular Cup',
    size: 'Cutout: 75 mm, Depth: 85 mm',
    bodyType: '12W Bridgelux COB LED Fixture',
    sku: 'ELC-DRK-COB',
    description: 'Glare-free deep recessed downlight with zero visible source luminance at 45 degree viewing angles.',
    applications: ['Galleries', 'Dining Rooms', 'Bedrooms'],
    specifications: [
      { key: 'UGR (Glare Index)', value: 'UGR < 10 Glare Free' },
      { key: 'Color Temperature', value: '3000K Warm White' },
    ],
    images: ['https://images.unsplash.com/photo-1513506003901-1e6a229e2d15?auto=format&fit=crop&w=1200&q=85'],
    featured: false,
    newArrival: true,
    popular: true,
    available: true,
    visible: true,
    displayOrder: 65,
  },
];

export async function syncRealProductImages() {
  try {
    const validNames = FIVE_PRODUCTS_PER_CATEGORY.map((p) => p.name);
    
    // Remove all extra products from database so only the exact 5 products per category remain
    const deleteRes = await Product.deleteMany({ name: { $nin: validNames } });
    if (deleteRes.deletedCount > 0) {
      console.log(`[ProductSync] Pruned ${deleteRes.deletedCount} extra products. Exactly 5 products per category retained.`);
    }

    const categories = await Category.find({});
    const categoryMap = new Map(categories.map((c) => [c.slug, c._id]));

    // Upsert the 20 products
    for (const item of FIVE_PRODUCTS_PER_CATEGORY) {
      const catId = categoryMap.get(item.categorySlug);
      const updateData: any = { ...item };
      if (catId) {
        updateData.category = catId;
      }
      await Product.findOneAndUpdate(
        { name: item.name },
        updateData,
        { upsert: true, new: true, setDefaultsOnInsert: true }
      );
    }

    console.log('[ProductSync] Exactly 20 products (5 per category) synced with pure material and physical apparatus images.');
  } catch (err) {
    console.error('[ProductSync] Error syncing product images:', err);
  }
}
